name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  animated_text_kit: ^4.2.1
  cupertino_icons: ^0.1.2
  firebase_core: ^1.17.1
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
